const skillCatalog = [
  {
    name: 'JavaScript',
    aliases: ['javascript', 'js', 'ecmascript'],
    group: 'Programming Language',
    category: 'IT',
    title: /frontend|backend|fullstack|node|react|javascript/i,
  },
  {
    name: 'TypeScript',
    aliases: ['typescript', 'ts'],
    group: 'Programming Language',
    category: 'IT',
    title: /typescript|\bts\b/i,
  },
  {
    name: 'React',
    aliases: ['react', 'reactjs', 'react.js'],
    group: 'Frontend Framework',
    category: 'IT',
    title: /frontend|react/i,
  },
  {
    name: 'Node.js',
    aliases: ['node.js', 'nodejs', 'node'],
    group: 'Runtime',
    category: 'IT',
    title: /backend|node|fullstack/i,
  },
  {
    name: 'Express',
    aliases: ['express', 'express.js', 'expressjs'],
    group: 'Node.js Framework',
    category: 'IT',
    title: /express/i,
  },
  {
    name: 'NestJS',
    aliases: ['nestjs', 'nest.js', 'nest js'],
    group: 'Node.js Framework',
    category: 'IT',
    title: /nestjs|nest\.js|nest js/i,
  },
  {
    name: 'REST API',
    aliases: ['rest api', 'restful api', 'rest', 'api'],
    group: 'API',
    category: 'IT',
    title: /backend|api|integration/i,
  },
  {
    name: 'SQL',
    aliases: ['sql', 'relational database', 'database'],
    group: 'SQL Database',
    category: 'IT',
    title: /backend|data|fullstack|database/i,
  },
  {
    name: 'PostgreSQL',
    aliases: ['postgresql', 'postgres', 'psql'],
    group: 'SQL Database',
    category: 'IT',
    title: /postgres|postgresql/i,
    implies: ['SQL'],
  },
  {
    name: 'MySQL',
    aliases: ['mysql', 'maria db', 'mariadb'],
    group: 'SQL Database',
    category: 'IT',
    title: /mysql|mariadb/i,
    implies: ['SQL'],
  },
  {
    name: 'MongoDB',
    aliases: ['mongodb', 'mongo db', 'mongo'],
    group: 'NoSQL Database',
    category: 'IT',
    title: /mongo|mongodb/i,
  },
  {
    name: 'Redis',
    aliases: ['redis', 'cache', 'caching'],
    group: 'Cache',
    category: 'IT',
    title: /redis|cache/i,
  },
  {
    name: 'Docker',
    aliases: ['docker', 'container', 'containers', 'containerization'],
    group: 'DevOps',
    category: 'IT',
    title: /devops|backend|docker/i,
  },
  {
    name: 'Kubernetes',
    aliases: ['kubernetes', 'k8s'],
    group: 'DevOps',
    category: 'IT',
    title: /kubernetes|k8s/i,
  },
  {
    name: 'Microservices',
    aliases: ['microservices', 'microservice', 'service oriented', 'distributed services'],
    group: 'Architecture',
    category: 'IT',
    title: /microservice|microservices/i,
  },
  {
    name: 'Git',
    aliases: ['git', 'github', 'gitlab', 'version control'],
    group: 'Tooling',
    category: 'IT',
    title: /developer|engineer|frontend|backend|fullstack/i,
  },
  {
    name: 'HTML',
    aliases: ['html', 'html5'],
    group: 'Frontend',
    category: 'IT',
    title: /frontend|ui/i,
  },
  {
    name: 'CSS',
    aliases: ['css', 'css3', 'tailwind', 'sass', 'scss'],
    group: 'Frontend',
    category: 'IT',
    title: /frontend|ui/i,
  },
  {
    name: 'Python',
    aliases: ['python'],
    group: 'Programming Language',
    category: 'IT',
    title: /data|python|ai|machine learning/i,
  },
  {
    name: 'Testing',
    aliases: ['testing', 'test case', 'automation test', 'automated testing', 'qa', 'qc'],
    group: 'Quality',
    category: 'IT',
    title: /qa|qc|tester|testing/i,
  },
  {
    name: 'SEO',
    aliases: ['seo', 'search engine optimization'],
    group: 'Marketing',
    category: 'Marketing',
    title: /seo|marketing/i,
  },
  {
    name: 'Content Marketing',
    aliases: ['content', 'copywriting', 'content marketing'],
    group: 'Marketing',
    category: 'Marketing',
    title: /content|marketing/i,
  },
  {
    name: 'Social Media',
    aliases: ['social media', 'facebook', 'tiktok', 'instagram'],
    group: 'Marketing',
    category: 'Marketing',
    title: /social|marketing/i,
  },
  {
    name: 'Analytics',
    aliases: ['analytics', 'google analytics', 'data analysis', 'reporting'],
    group: 'Analytics',
    category: 'Marketing',
    title: /analytics|marketing|data/i,
  },
  {
    name: 'Sales',
    aliases: ['sales', 'ban hang', 'kinh doanh'],
    group: 'Sales',
    category: 'Sales',
    title: /sales|account|business|kinh doanh/i,
  },
  {
    name: 'CRM',
    aliases: ['crm', 'hubspot', 'salesforce'],
    group: 'Sales',
    category: 'Sales',
    title: /sales|account|crm/i,
  },
  {
    name: 'Negotiation',
    aliases: ['negotiation', 'dam phan'],
    group: 'Sales',
    category: 'Sales',
    title: /sales|business|negotiation/i,
  },
  {
    name: 'Accounting',
    aliases: ['accounting', 'ke toan'],
    group: 'Accounting',
    category: 'Accounting',
    title: /accounting|ke toan/i,
  },
  {
    name: 'Excel',
    aliases: ['excel', 'spreadsheet', 'spreadsheets'],
    group: 'Office',
    category: 'Accounting',
    title: /accounting|finance|ke toan|analyst/i,
  },
  {
    name: 'Tax',
    aliases: ['tax', 'thue'],
    group: 'Accounting',
    category: 'Accounting',
    title: /tax|thue/i,
  },
  {
    name: 'Recruiting',
    aliases: ['recruiting', 'recruitment', 'tuyen dung'],
    group: 'HR',
    category: 'HR',
    title: /recruit|hr|nhan su/i,
  },
  {
    name: 'HR Operations',
    aliases: ['hr operations', 'human resources', 'nhan su'],
    group: 'HR',
    category: 'HR',
    title: /hr|nhan su/i,
  },
  {
    name: 'Communication',
    aliases: ['communication', 'giao tiep'],
    group: 'General',
    category: 'General',
    title: /support|sales|hr|account/i,
  },
];

const categoryFallbacks = [
  { pattern: /it|phan mem|developer|engineer|software/i, skills: ['JavaScript', 'SQL', 'Git'] },
  { pattern: /marketing|quang cao/i, skills: ['Content Marketing', 'SEO', 'Analytics'] },
  { pattern: /ban hang|kinh doanh|sales/i, skills: ['Sales', 'CRM', 'Negotiation'] },
  { pattern: /ke toan|finance|tai chinh/i, skills: ['Accounting', 'Excel', 'Tax'] },
  { pattern: /nhan su|hr|hanh chinh/i, skills: ['Recruiting', 'HR Operations', 'Communication'] },
];

module.exports = {
  categoryFallbacks,
  skillCatalog,
};
